## 1. OpenAI Gym Environment

In [1]:
import random
import math
import numpy as np
from collections import deque

# Setup the OpenAI Gym Environment

import gym

env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(1000):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
        

[-0.03806074 -0.01923468 -0.04273739  0.01498595]
[-0.03844544  0.17647329 -0.04243767 -0.29086893]
[-0.03491597  0.37217385 -0.04825505 -0.59662841]
[-0.02747249  0.17775922 -0.06018762 -0.31952741]
[-0.02391731 -0.01645621 -0.06657817 -0.04641625]
[-0.02424643 -0.21056342 -0.06750649  0.22453999]
[-0.0284577  -0.40465887 -0.06301569  0.49518818]
[-0.03655088 -0.59883819 -0.05311193  0.76736469]
[-0.04852764 -0.40302685 -0.03776464  0.45845427]
[-0.05658818 -0.20739196 -0.02859555  0.15411101]
[-0.06073602 -0.01187248 -0.02551333 -0.14745425]
[-0.06097347 -0.20661996 -0.02846242  0.1370718 ]
[-0.06510587 -0.40132293 -0.02572098  0.42064113]
[-0.07313233 -0.20584616 -0.01730816  0.11996183]
[-0.07724925 -0.40071591 -0.01490892  0.40713433]
[-0.08526357 -0.59562332 -0.00676623  0.69507989]
[-0.09717603 -0.79065077  0.00713536  0.98562512]
[-0.11298905 -0.59562511  0.02684787  0.69519185]
[-0.12490155 -0.79110895  0.0407517   0.99620426]
[-0.14072373 -0.98675149  0.06067579  1.30140211]


[-0.0187971  -0.01247362 -0.05736274 -0.07082777]
[-0.01904658  0.1834218  -0.05877929 -0.38104299]
[-0.01537814 -0.01081838 -0.06640015 -0.10745706]
[-0.01559451 -0.20492907 -0.06854929  0.16356004]
[-0.01969309 -0.00889619 -0.06527809 -0.14993641]
[-0.01987101  0.18709684 -0.06827682 -0.46247792]
[-0.01612908  0.38311394 -0.07752638 -0.7758763 ]
[-0.0084668   0.18913903 -0.09304391 -0.50855782]
[-0.00468402 -0.00455732 -0.10321506 -0.24658549]
[-0.00477516  0.19187571 -0.10814677 -0.56995829]
[-0.00093765 -0.00157663 -0.11954594 -0.31320828]
[-0.00096918 -0.19481071 -0.1258101  -0.0604887 ]
[-0.0048654  -0.38792531 -0.12701988  0.19000306]
[-0.0126239  -0.19123665 -0.12321982 -0.13989659]
[-0.01644864  0.0054149  -0.12601775 -0.46877244]
[-0.01634034  0.20207081 -0.1353932  -0.7983684 ]
[-0.01229892  0.3987647  -0.15136056 -1.13039321]
[-0.00432363  0.59550911 -0.17396843 -1.466466  ]
[ 0.00758655  0.40289119 -0.20329775 -1.23278941]
Episode finished after 25 timesteps
[ 0.03194056 -

[-0.09906405 -0.01163436  0.16493175  0.37744003]
[-0.09929673 -0.20866756  0.17248055  0.71724947]
[-0.10347008 -0.40570356  0.18682554  1.05887629]
[-0.11158416 -0.21348111  0.20800307  0.8301677 ]
Episode finished after 18 timesteps
[ 0.02168894 -0.00212763 -0.02473172  0.01301659]
[ 0.02164639 -0.19688633 -0.02447139  0.29779491]
[ 0.01770866 -0.39165105 -0.01851549  0.58266065]
[ 0.00987564 -0.19627465 -0.00686227  0.28420305]
[ 0.00595015 -0.39129806 -0.00117821  0.57471378]
[-0.00187581 -0.58640347  0.01031606  0.8670253 ]
[-0.01360388 -0.78166428  0.02765657  1.16293379]
[-0.02923717 -0.97713524  0.05091524  1.4641581 ]
[-0.04877987 -0.78267264  0.08019841  1.18780482]
[-0.06443333 -0.58867675  0.1039545   0.92129936]
[-0.07620686 -0.78503821  0.12238049  1.24475909]
[-0.09190763 -0.59168021  0.14727567  0.99278144]
[-0.10374123 -0.3988028   0.1671313   0.74974   ]
[-0.11171729 -0.59578716  0.1821261   1.09000756]
[-0.12363303 -0.7927809   0.20392625  1.43386054]
Episode finish

In [2]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)


In [3]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


## 2. Define Parameters

In [4]:
# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0 # Discount factor. Consideration of future rewards - same policies (the ones that balance the pole) are optimal 
          # at every step.
epsilon=1.0 # Exploration. Agent chooses action that it believes has the best long-term effect with probability 1- epsilon,
            # and it chooses an action uniformly at random, otherwise.  
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01 # the learning rate, determines to what extent the newly acquired information will override the old information. 
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

In [10]:
#Building Neural Network
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

In [11]:
#Necessary Functions
def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [12]:
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 100 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, epsilon)

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e


In [ ]:
import random
import gym
import math
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0
epsilon=1.0
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay    
        
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 20 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, get_epsilon(e))

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

run()

[Episode 0] - Mean survival time over last 100 episodes was 17.0 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 11.666666666666666 ticks.
[Episode 40] - Mean survival time over last 100 episodes was 10.682926829268293 ticks.
